// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go/service/s3"
	"go.mongodb.org/mongo-driver/mongo"
	"pixstall-commission/app/commission/delivery/http"
	mongo2 "pixstall-commission/app/commission/repo/mongo"
	"pixstall-commission/app/commission/usecase"
	"pixstall-commission/app/image/aws-s3"
)

// Injectors from wire.go:

func InitCommissionController(db *mongo.Database, awsS3 *s3.S3) http.CommissionController {
	repo := mongo2.NewMongoCommissionRepo(db)
	imageRepo := aws_s3.NewAWSS3ImageRepository(awsS3)
	useCase := usecase.NewCommissionUseCase(repo, imageRepo)
	commissionController := http.NewCommissionController(useCase)
	return commissionController
}
